// Code generated by "stringer -type=Mode -trimprefix=Mode"; DO NOT EDIT.

package gamedata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeUnknown-0]
	_ = x[ModeJump-1]
	_ = x[ModeOrbiting-2]
	_ = x[ModeCombat-3]
	_ = x[ModeAfterCombat-4]
	_ = x[ModeScavenging-5]
	_ = x[ModeAttack-6]
	_ = x[ModeSneaking-7]
	_ = x[ModeJustEntered-8]
	_ = x[ModeDocked-9]
}

const _Mode_name = "UnknownJumpOrbitingCombatAfterCombatScavengingAttackSneakingJustEnteredDocked"

var _Mode_index = [...]uint8{0, 7, 11, 19, 25, 36, 46, 52, 60, 71, 77}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
