// Code generated by "stringer -type=Mode -trimprefix=Mode"; DO NOT EDIT.

package gamedata

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[ModeUnknown-0]
	_ = x[ModeJump-1]
	_ = x[ModeOrbiting-2]
	_ = x[ModeScavenging-3]
	_ = x[ModeJustEntered-4]
}

const _Mode_name = "UnknownJumpOrbitingScavengingJustEntered"

var _Mode_index = [...]uint8{0, 7, 11, 19, 29, 40}

func (i Mode) String() string {
	if i < 0 || i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}
